### ISSUE TITLE
Can I get more info around setup?

### ISSUE THREAD

**Issue by suhasdeshpande** [babel/babel-bot#17]
Hi, 
    In AWS_SETUP.md you have GitHub step that shows how to create new API Token thus giving repo permission. And in the final step, you mention about adding ```Environment variables```  such as ```GITHUB_API_KEY``` and ```GITHUB_SECRET``` from Github step. Where is that defined in Github step? What is API_KEY and SECRET referring to? 

Thanks,
Suhas

**Comment by aaronang** [comment]
@suhasdeshpande Sorry for the late reply. For `GITHUB_API_KEY` use the token generated for the GitHub API in Step 7. For `GITHUB_SECRET` use the token generated in Step 4. If you have any other support questions, I would highly recommend you to join us on [Slack](https://slack.babeljs.io/).
