### ISSUE TITLE
Add babel-bot to the Babel org

### ISSUE THREAD

**Issue by xtuc** [babel/babel-bot#28]
The bot (hzoo there) is talking to itself.

The condition to skip the message is [here](https://github.com/babel/babel-bot/blob/master/src/handlers/issues/opened.js#L30), the user must be in Babel's org.

![screenshot from 2017-03-19 11-05-32](https://cloud.githubusercontent.com/assets/1493671/24079924/1fc8fc8c-0c94-11e7-84de-3acced9db785.png)

See https://github.com/babel/babylon/issues/420#issuecomment-287593549

**Comment by Daniel15** [comment]
Seems fixed
![](http://ss.dan.cx/2017/08/People_%C2%B7_Babel_-_Google_Chrome_12-16.42.15.png)
