### ISSUE TITLE
[Question] Bot behavior in 2016

### ISSUE THREAD

**Issue by Revadike** [babel/babel-bot#78]
In https://github.com/babel/babel/issues/4019, why does @babel-bot repeat comments originally made by others? Where do they come from?

**Comment by nicolo-ribaudo** [comment]
A few years ago we were using phabricator rather than GitHub issues to track bug reports.

We then migrated back to GitHub, and babel-bot transferred/copied all the comments using https://github.com/babel/phabricator-to-github

**Comment by Revadike** [comment]
Thank you
